Sergio/langtonant
fjcoding/AT15 pull request #95
Opened 2022-02-08 06:18 UTC by SerJimmy

2022-02-09 02:09 UTC, J0c4 requested changes
Nice work! your logic is not hard to understand in multiple parts. It can be improved if you try to create more methods to avoid groups of repeated code

2022-02-09 12:06 UTC, SerJimmy commented on src/main/java/org/fundacionjala/at15/katas/langtonant/sergio/Ant.java
> +            if (xPos == 0 && direction == "left"){
so, You are saying that I should move the wall to a different class.

2022-02-09 12:08 UTC, SerJimmy commented on src/main/java/org/fundacionjala/at15/katas/langtonant/sergio/Ant.java
> +            if (direction.equals("up")){
I understand that I have to create another method using setters and getters

2022-02-09 12:09 UTC, SerJimmy commented on src/main/java/org/fundacionjala/at15/katas/langtonant/sergio/Ant.java
> +            if (xPos == 0 && direction == "left"){
Oh sorry, I think I've got it

2022-02-09 13:41 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/langtonant/sergio/Ant.java
> +            if (xPos == 0 && direction == "left"){
It could be a method in this same class or a separated class, as long as it makes sense with the logic of the code

2022-02-09 13:42 UTC, J0c4 commented on src/main/java/org/fundacionjala/at15/katas/langtonant/sergio/Ant.java
> +            if (direction.equals("up")){
Yes, another method would be ok. Getters and setters might be optional

2022-02-10 03:12 UTC, J0c4 requested changes
Looks good! however, there are merge conflicts that need to be fixed first, please merge with dev/langtonant and push a new commit with conflicts solved

2022-02-10 13:59 UTC, J0c4 commented on .gitignore
> +bin
bin is duplicate, please remove one of them

2022-02-10 14:04 UTC, J0c4 approved these changes

2022-02-10 14:05 UTC, merged